### PR TITLE
Fix operation query for Cosmos messages

### PR DESCRIPTION
**Pull request by gagbo**
----

#

### CODE REVIEW

**Comment by gagbo** [comment]
That compilation error in the CI makes no sense at all :thinking:

**Review by ghost — APPROVED** [review]
Weird indeed. Just for my curiosity, can I see the compilation error?

**Comment by gagbo** [comment]
```
/root/lib-ledger-core/core/src/wallet/cosmos/CosmosLikeAccount.cpp: In instantiation of 'ledger::core::CosmosLikeAccount::getPendingRewards()::<lambda(auto:7&)> [with auto:7 = const std::shared_ptr<std::vector<ledger::core::cosmos::Reward> >]':
/usr/include/c++/6/type_traits:2481:26:   required by substitution of 'template<class _Fn, class ... _Args> static std::__result_of_success<decltype (declval<_Fn>()((declval<_Args>)()...)), std::__invoke_other> std::__result_of_other_impl::_S_test(int) [with _Fn = ledger::core::CosmosLikeAccount::getPendingRewards()::<lambda(auto:7&)>&; _Args = {const std::shared_ptr<std::vector<ledger::core::cosmos::Reward, std::allocator<ledger::core::cosmos::Reward> > >&}]'
/usr/include/c++/6/type_traits:2492:55:   required from 'struct std::__result_of_impl<false, false, ledger::core::CosmosLikeAccount::getPendingRewards()::<lambda(auto:7&)>&, const std::shared_ptr<std::vector<ledger::core::cosmos::Reward, std::allocator<ledger::core::cosmos::Reward> > >&>'
/usr/include/c++/6/type_traits:2496:12:   required from 'class std::result_of<ledger::core::CosmosLikeAccount::getPendingRewards()::<lambda(auto:7&)>&(const std::shared_ptr<std::vector<ledger::core::cosmos::Reward> >&)>'
/root/lib-ledger-core/core/src/wallet/cosmos/CosmosLikeAccount.cpp:814:33:   recursively required by substitution of 'template<class R> ledger::core::Future<R> ledger::core::Future<T>::map(const Context&, std::function<A(const T&)>) [with R = std::vector<std::shared_ptr<ledger::core::api::CosmosLikeReward> >]'
/root/lib-ledger-core/core/src/wallet/cosmos/CosmosLikeAccount.cpp:814:33:   required from here
/root/lib-ledger-core/core/src/wallet/cosmos/CosmosLikeAccount.cpp:810:131: error: cannot call member function 'std::__cxx11::string ledger::core::CosmosLikeAccount::getAddress() const' without object
                                                         rewardList.push_back(std::make_shared<CosmosLikeReward>(reward, getAddress()));
                                                                                                                         ~~~~~~~~~~^~
[ 53%] Building CXX object core/src/CMakeFiles/ledger-core-obj.dir/wallet/cosmos/CosmosLikeCurrencies.cpp.o
[ 53%] Building CXX object core/src/CMakeFiles/ledger-core-obj.dir/wallet/cosmos/CosmosLikeMessage.cpp.o
core/src/CMakeFiles/ledger-core-obj.dir/build.make:2779: recipe for target 'core/src/CMakeFiles/ledger-core-obj.dir/wallet/cosmos/CosmosLikeAccount.cpp.o' failed
make[2]: *** [core/src/CMakeFiles/ledger-core-obj.dir/wallet/cosmos/CosmosLikeAccount.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1384: recipe for target 'core/src/CMakeFiles/ledger-core-obj.dir/all' failed
make[1]: *** [core/src/CMakeFiles/ledger-core-obj.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by gagbo** [comment]
It might be that 2 parallel builds were launched by sequential PRs, so filesystem went out of sync

**Comment by ghost** [comment]
Does this PR fix the error?... I don't see how they are related? (you can merge anyway, it's just for my understanding)

**Pull request merged**
